DROP TABLE IF EXISTS
    films,
    MPA,
    film_genre,
    genres;



CREATE TABLE IF NOT EXISTS MPA (
                                   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name VARCHAR(50) NOT NULL,
                                   description VARCHAR(200)
);


CREATE TABLE IF NOT EXISTS films (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(50) NOT NULL,
                                     description varchar(200) NOT NULL,
                                     duration INTEGER NOT NULL,
                                     MPA_id INTEGER REFERENCES MPA(ID)
);



CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre (
                                          film_id INTEGER NOT NULL REFERENCES FILMS(ID),
                                          genre_id INTEGER NOT NULL REFERENCES GENRES(ID)
);

INSERT INTO MPA (name, description)
VALUES ('G','У фильма нет возрастных ограничений'),
       ('PG','Детям рекомендуется смотреть фильм с родителями'),
       ('PG-13','Детям до 13 лет просмотр не желателен'),
       ('R','Лицам до 17 лет просматривать фильм можно только в присутствии взрослого'),
       ('NC-17','Лицам до 18 лет просмотр запрещён');

INSERT INTO genres (name)
VALUES ('Комедия'),
       ('Драма'),
       ('Мультфильм'),
       ('Триллер'),
       ('Документальный'),
       ('Боевик');